### ISSUE TITLE
Could not pass event InventoryClickEvent

### ISSUE THREAD

**Issue by Meatroach** [WoodsMc09/DeathChest#1]
Hi.

I get the following error in regular intervals.

I could not check the cause just yet and will update as soon as I find any correlation

```
ERROR
17:59:00

Could not pass event InventoryClickEvent to DeathChest v1.1

Console
17:59:00

java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.Inventory.getSize()" because the return value of "org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()" is null
at me.woodsmc.deathchest.listener.GuiClickEvent.onClick(GuiClickEvent.java:21) ~[DeathChest-1.1.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor25.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-165]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2836) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-165]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-165]
at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-165]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-165]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-165]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-165]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-165]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-165]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Comment by WoodsMc09** [comment]
oh it’s an error in the code i’ll fix it

**Comment by Meatroach** [comment]
sweet, thank you! I really like the Plugin so far.

When I did a first test the chest didnt despawn though, is this intended? The sign did despawn. The Chest had no dye in it anymore after retrieving the loot

**Comment by WoodsMc09** [comment]
the newest version of the plugin should be fixed. and yes it is intended that the chest stays but the loot is gone, if that is a problem i may change that in the future

https://www.spigotmc.org/resources/deathchest.98898/

Thank you for your feedback!
